name: Docker Image CI

on:
  workflow_dispatch: 
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  build-host-amd64v4:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Build and push mainline/alpine (Linux x86_64-v4)
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: mainline-alpine.Dockerfile
          push: false
          tags: docker.io/denji/nginx-boringssl:mainline-alpine
          cache-from: type=registry,ref=docker.io/denji/nginx-boringssl:mainline-alpine
          cache-to: type=inline
